version: '3.8'

services:
  # --- BASES DE DATOS ---
  products-db:
    image: postgres:15-alpine
    container_name: products_db
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - products_data:/var/lib/postgresql/data

  inventory-db:
    image: postgres:15-alpine
    container_name: inventory_db
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" # Puerto externo diferente para no chocar
    volumes:
      - inventory_data:/var/lib/postgresql/data

  # --- MICROSERVICIOS ---
  product-service:
    build: ./product-service
    container_name: ms-products
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://products-db:5432/products_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      APP_API_KEY: "secret-key-123"
    depends_on:
      - products-db

  inventory-service:
    build: ./inventory-service
    container_name: ms-inventory
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      # URL interna de docker para comunicar servicios
      PRODUCTS_SERVICE_URL: http://product-service:8080 
      APP_API_KEY: "secret-key-123"
    depends_on:
      - inventory-db
      - product-service

volumes:
  products_data:
  inventory_data: